#https://gist.githubusercontent.com/janakiramm/7eb295185a157add51c03984a2e5a696/raw/7cfd80a7f892661ea5a230c84c4761be9428746a/triton-minio.sh

# Create Triton deployment
cat <<EOF > triton-deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: triton
  name: triton
  namespace: model-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: triton
  template:
    metadata:
      labels:
        app: triton
    spec:
      containers:
      - image: nvcr.io/nvidia/tritonserver:21.09-py3
        name: tritonserver
        command: ["/bin/bash"]
        args: ["-c", "cp /var/run/secrets/kubernetes.io/serviceaccount/ca.crt /usr/local/share/ca-certificates && update-ca-certificates && /opt/tritonserver/bin/tritonserver --model-store=s3://https://ip-10-20-0-72.us-west-2.compute.internal:9879 --strict-model-config=false"]
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_SECRET_ACCESS_KEY      
        ports:
          - containerPort: 8000
            name: http
          - containerPort: 8001
            name: grpc
          - containerPort: 8002
            name: metrics
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
EOF
